version: '3'

volumes:
  logs: {}
  db_data: {}
  redis_data: {}
  server_static: {}
  flower_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: raterapid_local_django_x
    container_name: raterapid_local_django
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
      - server_static:/app/staticfiles:rw
      - logs:/app/logs:rw
    env_file:
      - .env
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: raterapid_production_postgres
    container_name: raterapid_local_postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:6
    container_name: raterapid_local_redis

  celeryworker:
    <<: *django
    image: raterapid_local_celeryworker_x
    container_name: raterapid_local_celeryworker
    volumes:
      - logs:/app/logs:rw
    depends_on:
      - django
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: raterapid_local_celerybeat_x
    container_name: raterapid_local_celerybeat
    volumes:
      - logs:/app/logs:rw
    depends_on:
      - django
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: raterapid_local_flower
    container_name: raterapid_local_flower_X
    volumes:
      - logs:/app/logs:rw
      - flower_data:/data
    ports:
      - "5555:5555"
    command: /start-flower

  nginx:
    image: nginx:latest
    environment:
      - TZ=Africa/Cairo
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - logs:/app/logs:rw
    ports:
      - "8000:80"
    depends_on:
      - django
