# Generated by Django 4.1.9 on 2023-05-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyConversion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_currency",
                    models.CharField(
                        choices=[("USD", "Usd"), ("EGP", "Egp"), ("EUR", "Eur")],
                        max_length=3,
                        verbose_name="Base Currency",
                    ),
                ),
                (
                    "to_currency",
                    models.CharField(
                        choices=[("USD", "Usd"), ("EGP", "Egp"), ("EUR", "Eur")],
                        max_length=3,
                        verbose_name="Target Currency",
                    ),
                ),
                ("count", models.IntegerField(default=1, verbose_name="Request Count")),
            ],
            options={
                "verbose_name": "Currency Conversion",
                "verbose_name_plural": "Currency Conversions",
                "ordering": ["-count"],
                "unique_together": {("from_currency", "to_currency")},
            },
        ),
    ]
